# Generated by Django 4.2.4 on 2023-10-23 10:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("keywords", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("icon", models.ImageField(blank=True, upload_to="images/")),
                ("facebook", models.CharField(blank=True, max_length=50)),
                ("whatsapp", models.CharField(blank=True, max_length=50)),
                ("telegram", models.CharField(blank=True, max_length=50)),
                ("instagram", models.CharField(blank=True, max_length=50)),
                (
                    "about_us",
                    ckeditor_uploader.fields.RichTextUploadingField(blank=True),
                ),
                (
                    "contacts",
                    ckeditor_uploader.fields.RichTextUploadingField(blank=True),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
