# Generated by Django 4.2.4 on 2023-11-16 14:26

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Имя")),
                ("your_email", models.CharField(max_length=50, verbose_name="Почта")),
                ("subject", models.CharField(max_length=50, verbose_name="Тема")),
                (
                    "your_message",
                    models.TextField(
                        blank=True, max_length=255, verbose_name="Сообщение"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Read", "Read"),
                            ("Closed", "Closed"),
                        ],
                        default="New",
                        max_length=10,
                    ),
                ),
                ("ip", models.CharField(blank=True, max_length=20)),
                ("note", models.CharField(blank=True, max_length=100)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "Контакт", "verbose_name_plural": "Контакты",},
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Название")),
                ("slug", models.SlugField(unique=True, verbose_name="URL")),
                ("details", models.CharField(max_length=150, verbose_name="Детали")),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/%Y/%m/%d/", verbose_name="Картинка"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Место проведения"
                    ),
                ),
                (
                    "for_who",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Для кого?"
                    ),
                ),
                (
                    "descriptions",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, verbose_name="Описание"
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата события")),
                ("start_time", models.TimeField(verbose_name="Время начала")),
                ("end_time", models.TimeField(verbose_name="Время конца")),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="Важное"),
                ),
                (
                    "is_attractive",
                    models.BooleanField(default=False, verbose_name="Интересное"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("True", "True"), ("False", "False")],
                        default=True,
                        max_length=10,
                        verbose_name="Опубликовать",
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "Встреча", "verbose_name_plural": "Встречи",},
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("keywords", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("icon", models.ImageField(blank=True, upload_to="images/")),
                ("facebook", models.CharField(blank=True, max_length=50)),
                ("whatsapp", models.CharField(blank=True, max_length=50)),
                ("telegram", models.CharField(blank=True, max_length=50)),
                ("email", models.CharField(blank=True, max_length=50)),
                ("instagram", models.CharField(blank=True, max_length=50)),
                (
                    "about_us",
                    ckeditor_uploader.fields.RichTextUploadingField(blank=True),
                ),
                (
                    "contacts",
                    ckeditor_uploader.fields.RichTextUploadingField(blank=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("True", "True"), ("False", "False")],
                        default=0,
                        max_length=10,
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "Настройка", "verbose_name_plural": "Настройки",},
        ),
    ]
