# Generated by Django 4.2.4 on 2023-12-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_events_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="date",
            field=models.DateField(db_index=True, verbose_name="Дата события"),
        ),
    ]
