# Generated by Django 4.2.4 on 2023-10-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_setting_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="status",
            field=models.CharField(
                choices=[("True", "True"), ("False", "False")], default=0, max_length=10
            ),
        ),
    ]
