# Generated by Django 4.2.4 on 2023-10-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_setting_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("your_email", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=50)),
                ("your_message", models.TextField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Read", "Read"),
                            ("Closed", "Closed"),
                        ],
                        default="New",
                        max_length=10,
                    ),
                ),
                ("ip", models.CharField(blank=True, max_length=20)),
                ("note", models.CharField(blank=True, max_length=100)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
