# Generated by Django 4.2.4 on 2023-10-28 15:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_contactmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meetings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Название")),
                ("details", models.CharField(max_length=150, verbose_name="Детали")),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/%Y/%m/%d/", verbose_name="Картинка"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Место проведения"
                    ),
                ),
                (
                    "descriptions",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, verbose_name="Описание"
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата события")),
                ("start_time", models.TimeField(verbose_name="Время начала")),
                ("end_time", models.TimeField(verbose_name="Время конца")),
                (
                    "status",
                    models.CharField(
                        choices=[("True", "True"), ("False", "False")],
                        default=0,
                        max_length=10,
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(max_length=50, verbose_name="Тема"),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="your_email",
            field=models.CharField(max_length=50, verbose_name="Почта"),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="your_message",
            field=models.TextField(
                blank=True, max_length=255, verbose_name="Сообщение"
            ),
        ),
    ]
