# Generated by Django 4.2.4 on 2023-10-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_rename_meetings_events_alter_contactmessage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="is_attractive",
            field=models.BooleanField(default=False, verbose_name="Интересное"),
        ),
        migrations.AddField(
            model_name="events",
            name="is_important",
            field=models.BooleanField(default=False, verbose_name="Важное"),
        ),
        migrations.AlterField(
            model_name="events",
            name="status",
            field=models.CharField(
                choices=[("True", "True"), ("False", "False")],
                default=True,
                max_length=10,
                verbose_name="Опубликовать",
            ),
        ),
    ]
