# Generated by Django 4.2.4 on 2023-10-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_events_is_attractive_events_is_important_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="slug",
            field=models.SlugField(null=True, unique=True, verbose_name="URL"),
        ),
    ]
