# Generated by Django 4.2.4 on 2023-10-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_events_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="URL"),
        ),
    ]
