# Generated by Django 4.2.4 on 2023-11-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_events_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="for_who",
            field=models.CharField(blank=True, max_length=50, verbose_name="Для кого?"),
        ),
    ]
